# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/cross_compile.yml

on:
  push:
    tags:
      - '*'

name: Cross-compile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabihf
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      # TODO: strip executable?
      # TODO: tarball
      # TODO: upload tarball
      - name: Rename built binary
        run: mv target/${{ matrix.target }}/release/rum rum-${{ matrix.target }}
      - name: Publish built binary
        uses: softprops/action-gh-release@v1
        with:
          # name: rum-${{ matrix.target }}
          files: rum-${{ matrix.target }}
